### ISSUE TITLE
Floating  Ore Veins

### ISSUE THREAD

**Issue by Leafrmao** [orlouge/custom-ore-veins#2]
somehow the ore veins will float in the air  
Maybe add a compulsory solid block replacing rule will fix this?
Does it relates to generating event orders?
![(2JKXQM))~NEDBJ 7 O0(4K](https://github.com/orlouge/custom-ore-veins/assets/170778413/431996de-336d-4eb6-994e-3282a3e30e48)
![QK% OIXIQA(MHYZ_FR@U16N](https://github.com/orlouge/custom-ore-veins/assets/170778413/56cbc2b2-7d5b-4945-8b07-009cd07de2fc)

**Comment by VinterNacht** [comment]
Those are BEAUTIFUL ore veins... What's weird is I believe in order to end up like that, they have to have generated AFTER cave gen, rather than before.  That's not something you control, it's just the way MC WorldGen works... Truly a strange thing.

**Comment by orlouge** [comment]
The ore veins are generated before the caves. They're not features but a special step in world generation, most likely for performance reasons, and this mod expands on that. The reason vanilla veins don't have floating blocks is that iron and copper ores are in #overworld_carver_replaceables. You can add the custom vein blocks to that tag to make it so that the caves destroy those blocks.
